from . import start
from . import help
from . import set_language
from . import admin_button
from . import test
from . import oddiy_test
from . import check_answer
from . import fanli_test
from . import my_tests